### ISSUE TITLE
Steal TSA broken

### ISSUE THREAD

**Issue by Darrman** [Kirbseverywhere/Fire-Emblem-3-Universes#48] opened 2019-12-20 16:17 UTC
![image](https://user-images.githubusercontent.com/30606600/71268137-1f69d800-2344-11ea-907b-8800fb2596d0.png)

Can be reproduced on any enemy with a shield in AB1.

**Comment by sme23** [comment] 2020-05-04 22:32
duplicate of #23

**Closed as completed by sme23** 2020-05-04 22:32 UTC
Labels: Visual Bug
